name: Actions Workflow

on:  
  #schedule:
  # at minute 1 on every hour
  #  - cron: "1 * * * *"    
  # push 
  pull_request:
    types: [closed, assigned, opened, reopened]
    
jobs:
  run-guthub-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Snezhi
      
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
        
        